version: 2

s17:26:19 version: 2

sources:
  - name: raw_data
    database: healthcare_raw
    tables:
      - name: allergies
      - name: careplans
      - name: claims
      - name: claims_transactions
      - name: conditions
      - name: devices
      - name: encounters
      - name: imaging_studies
      - name: immunizations
      - name: medications
      - name: observations
      - name: organizations
      - name: patients
      - name: payer_transitions
      - name: payers
      - name: procedures
      - name: providers
      - name: supplies
      - name: table_column_preview